# Generated by Django 4.1.4 on 2022-12-22 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
