# Generated by Django 4.1.4 on 2022-12-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_blog_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('mraks', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
                ('blog_date', models.DateTimeField(auto_now=True)),
                ('blog_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
